# Generated by Django 2.2.6 on 2020-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0012_addmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcom2',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addcom2',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addcrime',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addcrime',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addfir',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addfir',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addhistory',
            name='case1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addhistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addmissing',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addmissing',
            name='date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addmissing',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addnews',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addnews',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addwanted',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addwanted',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addwanted',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
